---
latest_release_filename: "/Users/emrah/Development/cloud-foundry/hazelcast-cloudfoundry/hazelcast-mancenter-for-pcf/release/releases/hazelcast-mancenter-for-pcf/hazelcast-mancenter-for-pcf-1.0.2.yml"
